language:
  node_js
sudo: false
node_js: 
  - 12
  - 11
  - 10
  - 9
os:
  - linux
  - osx
arch:
  - arm64
  - amd64
branches:
  only:
    - devel
    - master
install:
  - npm i
before_script:
  - npm test
script:
  - node index.js
